title: Prasvasa
description: A starter site for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/prasvasa/prasvasa-docs/
  
color_scheme: dark
